version: '3.8'

services:
  ooh_postgis:
    image: postgis/postgis:latest
    container_name: ooh_postgis
    environment:
      POSTGRES_DB: ooh_gis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: always

  ooh_martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    container_name: ooh_martin
    environment:
      # Pastikan DB di bagian akhir adalah ooh_gis!
      DATABASE_URL: postgresql://postgres:postgres@ooh_postgis:5432/ooh_gis
    ports:
      - "3000:3000"
    depends_on:
      - ooh_postgis
    restart: always

volumes:
  postgis_data: